### PR TITLE
Fix page not found errors

### LINKED ISSUE #103: Existing links
There are PMR2 links in https://sparc.science/datasets/462?type=simulation&datasetDetailsTab=abstract. 
These links should work in PMR3.

### LINKED ISSUE #154: Page not found errors in exposures
The following page (and some other similar pages) is showing as 404. This is because of the URL structure, which might be related to #103.
https://physiome.github.io/pmrapp-frontend/exposures/d36/experiments/cell/mixed_pacing_experiment_QuinnKohl2016.cellml

### PR DESCRIPTION
**Pull request by akhuoa**
Fixes #154 and #103.

- Support alias `e` for `exposures` path.
**Before**: https://physiome.github.io/pmrapp-frontend/e/d67 
**After**: https://akhuoa.github.io/pmrapp-frontend/e/d67 

- Support workspace files with different commits.
**Before**: https://physiome.github.io/pmrapp-frontend/workspaces/earm_noble_1990/file/0f4051afdbdda6e9e5aed31df87ab5f2713be81f 
**After**: https://akhuoa.github.io/pmrapp-frontend/workspace/earm_noble_1990/file/0f4051afdbdda6e9e5aed31df87ab5f2713be81f 
**After**: https://akhuoa.github.io/pmrapp-frontend/workspace/c99/file/04f5e29e0ce36d3be2b18f87d1891d2488ead18e 

- Support `@@file` for workspaces. _(issue #103)_
https://akhuoa.github.io/pmrapp-frontend/workspace/c99/@@file

_**Note:** the latest exposure `e/d77` from https://sparc.science/datasets/462?type=simulation&datasetDetailsTab=abstract is not migrated yet._

### CODE REVIEW

File: src/router/index.ts [hunk 1]
```diff
@@ -34,41 +66,54 @@ const router = createRouter({
...
-      alias: ['/exposure/:alias'],
+      alias: createAliases(exposureAliasBases, '/:alias', '/:alias/view'),
       meta: { title: `Exposure Detail – ${title}` },
     },
     {
       path: '/exposures/:alias/:file',
       name: 'exposure-file-detail',
       component: ExposureDetailView,
-      alias: ['/exposure/:alias/:file'],
+      alias: createPluralRouteAliases('/exposures', exposureAliasBases, exposureFileRouteSuffixes),
```
Comment (agarny) [inline src/router/index.ts]: For consistency, you  might want to format this as follows:
```typescript
      alias: createPluralRouteAliases(
        '/exposures',
        exposureAliasBases,
        exposureFileRouteSuffixes
      ),
```

**Review by agarny — CHANGES_REQUESTED** [review]
Just a  minor formatting issue.

File: src/router/index.ts (hunk 1 above)
Comment (akhuoa) [reply src/router/index.ts]: Thanks, it was auto-formatted by biome. 
Now I've formatted it ([1748caa](https://github.com/Physiome/pmrapp-frontend/pull/159/commits/1748caa3dbfea2728ae05ab42f3ea31bf316d8e5)) and added biome ignore ([917c133](https://github.com/Physiome/pmrapp-frontend/pull/159/commits/917c1332cc949f68853a179287f54069f1928dfb)).

**Review by agarny — APPROVED** [review]
